//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 Microsoft Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHCOSRelease) DeepCopyInto(out *RHCOSRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new RHCOSRelease.
func (in *RHCOSRelease) DeepCopy() *RHCOSRelease {
	if in == nil {
		return nil
	}
	out := new(RHCOSRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RHCOSRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHCOSReleaseArchStatus) DeepCopyInto(out *RHCOSReleaseArchStatus) {
	*out = *in
	return
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new RHCOSReleaseArchStatus.
func (in *RHCOSReleaseArchStatus) DeepCopy() *RHCOSReleaseArchStatus {
	if in == nil {
		return nil
	}
	out := new(RHCOSReleaseArchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHCOSReleaseList) DeepCopyInto(out *RHCOSReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RHCOSRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new RHCOSReleaseList.
func (in *RHCOSReleaseList) DeepCopy() *RHCOSReleaseList {
	if in == nil {
		return nil
	}
	out := new(RHCOSReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RHCOSReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHCOSReleaseSpec) DeepCopyInto(out *RHCOSReleaseSpec) {
	*out = *in
	if in.ARMFeatures != nil {
		in, out := &in.ARMFeatures, &out.ARMFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.X86Features != nil {
		in, out := &in.X86Features, &out.X86Features
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new RHCOSReleaseSpec.
func (in *RHCOSReleaseSpec) DeepCopy() *RHCOSReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(RHCOSReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHCOSReleaseStatus) DeepCopyInto(out *RHCOSReleaseStatus) {
	*out = *in
	if in.Architectures != nil {
		in, out := &in.Architectures, &out.Architectures
		*out = make(map[string]RHCOSReleaseArchStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastInstallerSync != nil {
		in, out := &in.LastInstallerSync, &out.LastInstallerSync
		*out = (*in).DeepCopy()
	}
	if in.LastMarketplaceSync != nil {
		in, out := &in.LastMarketplaceSync, &out.LastMarketplaceSync
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new RHCOSReleaseStatus.
func (in *RHCOSReleaseStatus) DeepCopy() *RHCOSReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(RHCOSReleaseStatus)
	in.DeepCopyInto(out)
	return out
}
