apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.readonly.serviceAccount.name }}
  namespace: '{{ .Release.Namespace }}'
  annotations:
    azure.workload.identity/client-id: '{{ .Values.readonly.serviceAccount.workloadIdentityClientId }}'
    azure.workload.identity/tenant-id: '{{ .Values.readonly.serviceAccount.workloadIdentityTenantId }}'
